name: Broken link check
on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@master
        with:
          url: "https://github.com/hleb-kastseika/belarusian-it-communities/blob/master/README.md"
          honorRobotExclusions: true
          ignorePatterns: ""
          recursiveLinks: false
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
