name: Check broken links
on: [push]

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://github.com/hleb-kastseika/belarusian-it-communities/blob/master/README.md
          cmd_params: "--one-page-only --max-connections=3 --color=always --buffer-size=16000 --rate-limit=1 --skip-tls-verification=true"
