name: Check broken links
on: [push]

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://github.com/hleb-kastseika/belarusian-it-communities/blob/master/README.md
          cmd_params: "--verbose --one-page-only --color=always --buffer-size=16000 --rate-limit=1 --header='User-Agent:curl/7.54.0' --skip-tls-verification --exclude=.*docs.github.com.* --exclude=.*github.com/hleb-kastseika/belarusian-it-communities.* --exclude=.*docs.github.com.* --exclude=.*github-cloud.s3.amazonaws.com.* --exclude=.*github-cloud.s3.amazonaws.com.*"
