name: Check broken links and trigger deploy to website
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: 
      - closed
  schedule:
    - cron: "0 0 * * 0"

jobs:
  broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://github.com/hleb-kastseika/belarusian-it-communities/blob/master/README.md
          cmd_params: >
            --verbose
            --one-page-only
            --color=always
            --buffer-size=16000
            --rate-limit=1
            --max-connections=1
            --skip-tls-verification
            --exclude=.*docs.github.com.*
            --exclude=.*education.github.com.*
            --exclude=.*github.com/hleb-kastseika/belarusian-it-communities.*
            --exclude=.*docs.github.com.*
            --exclude=.*github-cloud.s3.amazonaws.com.*
            --exclude=.*user-images.githubusercontent.com.*
            --exclude=.*linkedin.com.*
      - name: Trigger downstream workflow
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACTIONS_KEY}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/hleb-kastseika/hleb-dev-website/actions/workflows/firebase-hosting-merge.yml/dispatches \
          -d '{"ref": "master"}'
