name: Check broken links
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 0 * * 0"

jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://github.com/hleb-kastseika/belarusian-it-communities/blob/master/README.md
          cmd_params: >
            --verbose
            --one-page-only
            --color=always
            --buffer-size=16000
            --rate-limit=1
            --max-connections=1
            --skip-tls-verification
            --exclude=.*docs.github.com.*
            --exclude=.*github.com/hleb-kastseika/belarusian-it-communities.*
            --exclude=.*docs.github.com.*
            --exclude=.*github-cloud.s3.amazonaws.com.*
            --exclude=.*user-images.githubusercontent.com.*
            --header="user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
            --header="referer:https://linkedin.com"
            --header="accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
            --header="accept-encoding:gzip, deflate, br"
            --header="accept-language:en-US,en;q=0.8"
            --header="cache-control:no-cache"
            --header="pragma:no-cache"
            --header="upgrade-insecure-requests:1"
